<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>comment</key>
    <string>CK2 Mod Syntax: version 0.1</string>
    <key>fileTypes</key>
    <array>
        <string>ck2</string>
    </array>
    <key>firstLineMatch</key>
    <string>^#CK2</string>
    <key>foldingStartMarker</key>
    <string>^.*\bfunction\s*(\w+\s*)?\([^\)]*\)(\s*\{[^\}]*)?\s*$</string>
    <key>foldingStopMarker</key>
    <string>^\s*\}</string>
    <key>keyEquivalent</key>
    <string>^~J</string>
    <key>name</key>
    <string>CK2 Mod</string>
    <key>patterns</key>
    <array>
        <dict>
            <key>comment</key>
            <string>node.js shebang</string>
            <key>match</key>
            <string>^#CK2</string>
            <key>name</key>
            <string>comment.line.js</string>
        </dict>
        <dict>
            <key>captures</key>
            <dict>
                <key>1</key>
                <dict>
                    <key>name</key>
                    <string>punctuation.definition.comment.conky</string>
                </dict>
            </dict>
            <key>match</key>
            <string>(\s)*(#).*$\n?</string>
            <key>name</key>
            <string>comment.line.hash.ini</string>
        </dict>
        <dict>
            <key>captures</key>
            <dict>
                <key>1</key>
                <dict>
                    <key>name</key>
                    <string>punctuation.definition.parameters.begin.python</string>
                </dict>
            </dict>
            <key>match</key>
            <string>(hobbit)</string>
            <key>name</key>
            <string>punctuation.definition.parameters.begin.python</string>
        </dict>
        <dict>
            <key>captures</key>
            <dict>
                <key>1</key>
                <dict>
                    <key>name</key>
                    <string>support.class.js</string>
                </dict>
                <key>2</key>
                <dict>
                    <key>name</key>
                    <string>support.constant.js</string>
                </dict>
                <key>3</key>
                <dict>
                    <key>name</key>
                    <string>entity.name.function.js</string>
                </dict>
                <key>4</key>
                <dict>
                    <key>name</key>
                    <string>keyword.operator.js</string>
                </dict>
            </dict>
            <!-- Light Blue -->
            <key>comment</key>
            <string>match stuff like: Sound.prototype.play = myfunc</string>
            <key>match</key>
            <!-- 
            <string>([a-zA-Z_?.$][\w?.$]*)\.(prototype)\.([a-zA-Z_?.$][\w?.$]*)\s*(=)\s*</string>
            -->
            <string>(kdsfafaflys)</string>
            <key>name</key>
            <string>meta.function.js</string>
        </dict>
        <dict>
            <key>match</key>
            <string>\b((0(x|X)[0-9a-fA-F]+)|([0-9]+(\.[0-9]+)?))\b</string>
            <key>name</key>
            <string>constant.numeric.js</string>
        </dict>
        <dict>
            <key>begin</key>
            <string>'</string>
            <key>beginCaptures</key>
            <dict>
                <key>0</key>
                <dict>
                    <key>name</key>
                    <string>punctuation.definition.string.begin.js</string>
                </dict>
            </dict>
            <key>end</key>
            <string>'</string>
            <key>endCaptures</key>
            <dict>
                <key>0</key>
                <dict>
                    <key>name</key>
                    <string>punctuation.definition.string.end.js</string>
                </dict>
            </dict>
            <key>name</key>
            <string>string.quoted.single.js</string>
            <key>patterns</key>
            <array>
                <dict>
                    <key>match</key>
                    <string>\\(x\h{2}|[0-2][0-7]{,2}|3[0-6][0-7]?|37[0-7]?|[4-7][0-7]?|.)</string>
                    <key>name</key>
                    <string>constant.character.escape.js</string>
                </dict>
            </array>
        </dict>
        <dict>
            <key>begin</key>
            <string>"</string>
            <key>beginCaptures</key>
            <dict>
                <key>0</key>
                <dict>
                    <key>name</key>
                    <string>punctuation.definition.string.begin.js</string>
                </dict>
            </dict>
            <key>end</key>
            <string>"</string>
            <key>endCaptures</key>
            <dict>
                <key>0</key>
                <dict>
                    <key>name</key>
                    <string>punctuation.definition.string.end.js</string>
                </dict>
            </dict>
            <key>name</key>
            <string>string.quoted.double.js</string>
            <key>patterns</key>
            <array>
                <dict>
                    <key>match</key>
                    <string>\\(x\h{2}|[0-2][0-7]{,2}|3[0-6][0-7]|37[0-7]?|[4-7][0-7]?|.)</string>
                    <key>name</key>
                    <string>constant.character.escape.js</string>
                </dict>
            </array>
        </dict>
        <dict>
            <key>begin</key>
            <string>/\*\*(?!/)</string>
            <key>captures</key>
            <dict>
                <key>0</key>
                <dict>
                    <key>name</key>
                    <string>punctuation.definition.comment.js</string>
                </dict>
            </dict>
            <key>end</key>
            <string>\*/</string>
            <key>name</key>
            <string>comment.block.documentation.js</string>
        </dict>
        <dict>
            <key>begin</key>
            <string>/\*</string>
            <key>captures</key>
            <dict>
                <key>0</key>
                <dict>
                    <key>name</key>
                    <string>punctuation.definition.comment.js</string>
                </dict>
            </dict>
            <key>end</key>
            <string>\*/</string>
            <key>name</key>
            <string>comment.block.js</string>
        </dict>
        <dict>
            <key>captures</key>
            <dict>
                <key>1</key>
                <dict>
                    <key>name</key>
                    <string>punctuation.definition.comment.js</string>
                </dict>
            </dict>
            <key>match</key>
            <string>(//).*$\n?</string>
            <key>name</key>
            <string>comment.line.double-slash.js</string>
        </dict>
        <dict>
            <key>captures</key>
            <dict>
                <key>0</key>
                <dict>
                    <key>name</key>
                    <string>punctuation.definition.comment.html.js</string>
                </dict>
                <key>2</key>
                <dict>
                    <key>name</key>
                    <string>punctuation.definition.comment.html.js</string>
                </dict>
            </dict>
            <key>match</key>
            <string>(&lt;!--|--&gt;)</string>
            <key>name</key>
            <string>comment.block.html.js</string>
        </dict>
        <!-- Character event stuff (Light Blue) -->
        <dict>
            <key>match</key>
            <string>\b(option|name|ai_chance|trigger|holder_scope|target|casus_belli|reverse_war|k_(a-z)|e_(a-z)|id|desc|hide_from|is_triggered_only|opinion|who|modifier|hidden_tooltip|letter_event|entry|picture|dynasty|is_liege_or_above|capital_scope|liege|demesne_size|war|has_character_flag_tier|location|is_capital|de_jure_liege_or_above|mean_time_to_happen|days|flag|trait|years|months|set_character_flag|clr_character_flag|character|add_trait|age)\b</string>
            <key>name</key>
            <string>storage.type.js</string>
        </dict>
        <!-- Pink -->
        <dict>
            <key>match</key>
            <string>\b(AND|OR|NOT|FROM|FROMFROM|which|factor|ROOT|PREV|PREVPREV|ROOTROOT|dejure_kingdom_claim|yes|no|defended_conquest|value|tooltip)\b</string>
            <key>name</key>
            <string>storage.modifier.js</string>
        </dict>
        <!-- Pink -->
        <dict>
            <key>match</key>
            <string>\b(if|limit|character_event|province_event|immediate)\b</string>
            <key>name</key>
            <string>keyword.control.js</string>
        </dict>
        <!-- Pink -->
        <dict>
            <key>match</key>
            <string>\b(afafafaf)\b</string>
            <key>name</key>
            <string>keyword.operator.js</string>
        </dict>
        <!-- Purple -->
        <dict>
            <key>match</key>
            <string>\b(ambitious|greedy|charitable|envious|slothful|fair|diligent)\b</string>
            <key>name</key>
            <string>constant.language.boolean.false.js</string>
        </dict>
        <dict>
            <!-- Purple -->
            <key>match</key>
            <string>\b(DUKE|KING|EMPEROR|COUNT|count|duke|king|emperor)\b</string>
            <key>name</key>
            <string>constant.language.js</string>
        </dict>
        <dict>
            <key>begin</key>
            <string>(?&lt;=[=(:]|^|return|&amp;&amp;|\|\||!)\s*(/)(?![/*+{}?])</string>
            <key>beginCaptures</key>
            <dict>
                <key>1</key>
                <dict>
                    <key>name</key>
                    <string>punctuation.definition.string.begin.js</string>
                </dict>
            </dict>
            <key>end</key>
            <string>(/)[igm]*</string>
            <key>endCaptures</key>
            <dict>
                <key>1</key>
                <dict>
                    <key>name</key>
                    <string>punctuation.definition.string.end.js</string>
                </dict>
            </dict>
            <key>name</key>
            <string>string.regexp.js</string>
            <key>patterns</key>
            <array>
                <dict>
                    <key>match</key>
                    <string>\\.</string>
                    <key>name</key>
                    <string>constant.character.escape.js</string>
                </dict>
            </array>
        </dict>
        <dict>
            <key>match</key>
            <string>\;</string>
            <key>name</key>
            <string>punctuation.terminator.statement.js</string>
        </dict>
        <dict>
            <key>match</key>
            <string>,[ |\t]*</string>
            <key>name</key>
            <string>meta.delimiter.object.comma.js</string>
        </dict>
        <dict>
            <key>match</key>
            <string>\.</string>
            <key>name</key>
            <string>meta.delimiter.method.period.js</string>
        </dict>
        <dict>
            <key>match</key>
            <string>\{|\}</string>
            <key>name</key>
            <string>meta.brace.curly.js</string>
        </dict>
        <dict>
            <key>match</key>
            <string>\(|\)</string>
            <key>name</key>
            <string>meta.brace.round.js</string>
        </dict>
        <dict>
            <key>match</key>
            <string>\[|\]</string>
            <key>name</key>
            <string>meta.brace.square.js</string>
        </dict>
    </array>
    <key>scopeName</key>
    <string>source.txt</string>
    <key>uuid</key>
    <string>93E017CC-6F27-11D9-90EB-000D93589AF6</string>
</dict>
</plist>
